name: MobGriefControl
main: com.github.drewburr.mobgriefcontrol.MobGriefControl
version: 2.0.0
author: drewburr
api-version: '1.21.11'
folia-supported: true

commands:
  mobgriefcontrol:
    description: Shows MobGriefControl help.
    usage: /<command>
    aliases: [mobgrief]
permissions:
  mobgriefcontrol.admin:
    description: For Admin only, Overrides all permissions.
    default: op
  mobgriefcontrol.op:
    description: Overrides most permissions.
    default: op
  mobgriefcontrol.showUpdateAvailable:
    description: Shows player if there is an update on login.
    default: op
  mobgriefcontrol.toggledebug:
    description: Allows the player to use "/mobgriefcontrol toggledebug" command.
    default: op
