name: MobGriefControl
main: com.github.drewburr.mobgriefcontrol.MobGriefControl
version: 1.14_1.0.9
author: JoelYahwehOfWar
api-version: 1.14
folia-supported: true

commands:
  mobgriefcontrol:
    description: Shows MobGriefControl help.
    usage: /<command>
    aliases: [mobgrief]
permissions:
  mobgriefcontrol.admin:
    description: For Admin only, Overrides all permissions.
    default: false
  mobgriefcontrol.op:
    description: Overrides most permissions.
    default: false
  mobgriefcontrol.showUpdateAvailable:
    description: Shows player if there is an update on login.
    default: op
  mobgriefcontrol.toggledebug:
    description: Allows the player to use "/mmh toggledebug" command.
    default: op
